### ISSUE TITLE
SampleGetFilesWithNoDiscoveries throws an error at line 102 involving sort method

### ISSUE THREAD

**Issue by MayuriMangireddy** [blackducksoftware/sdk-client-tools-protex#16]
Downloaded 7.3 SDK Samples and one of the samples 'SampleGetFilesWithNoDiscoveries' gives an error "The method sort(new Comparator<CodeTreeNode>(){}) is undefined for the type List<CodeTreeNode>" for sort method at line 102.

**Comment by romeara** [comment]
This is caused by use of a Java 8 API within the Java 6 environment of the project. It should be changed to use Collections.sort() instead

**Comment by romeara** [comment]
Fixed by recent pull request

**Comment by MayuriMangireddy** [comment]
Verified by downloading latest samples. No longer an issue.

**Comment by romeara** [comment]
Pull request resolving this issue is present in 7.3 release artifacts
